version : '3.8'

services:
  sqlite-viewer:
    container_name: sqlite-viewer
    image: coleifer/sqlite-web
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
    command: sqlite_web -H 0.0.0.0  /data/database.sqlite
