version : '3.8'

services:
  sm-mysqldb :
    container_name : 'sm-mysqldb'
    image : 'mysql:8.0'
    environment :
      MYSQL_ROOT_PASSWORD : software
      MYSQL_DATABASE : software_management
    volumes :
      - type : bind
        source : ./data/mysql/db
        target : /var/lib/mysql

      - type : bind
        source : ./data/mysql/log
        target : /var/log/mysql
    ports:
      - "6000:3306"

